// Terms of use and privacy policy. One source for the three languages; the pages only render these sections.
// Keep in sync with what the system actually does (auth, collection, Mercado Pago, support) whenever that changes.
export const LEGAL_UPDATED = '2026-09-18';
export const LEGAL_CONTACT = 'contato@cs13a0.com';

export interface LegalSection { heading: string; paragraphs: string[] }
export interface LegalDocument { title: string; updated: string; intro: string; sections: LegalSection[] }
type Language = 'pt-BR' | 'en' | 'es';

const PRIVACY: Record<Language, LegalDocument> = {
  'pt-BR': {
    title: 'Política de Privacidade',
    updated: 'Última atualização: 18/09/2026',
    intro: 'Esta política explica quais dados o cs13a0 trata, para quê, com quem compartilha e como você exerce seus direitos, conforme a Lei Geral de Proteção de Dados (Lei 13.709/2018). O cs13a0 é um projeto independente mantido por uma pessoa física no Brasil. Contato do responsável: contato@cs13a0.com.',
    sections: [
      { heading: 'Jogar sem conta', paragraphs: ['O modo offline e o draft online funcionam sem cadastro. Preferências (idioma, tema, velocidade) e a última run ficam no localStorage do seu navegador e não são enviadas a nós.', 'Nas salas online, nome do jogador, nome da organização, picks e resultados ficam na memória do servidor só enquanto a sala existe. Um token anônimo de retomada fica no seu navegador por poucos minutos.'] },
      { heading: 'Conta (opcional)', paragraphs: ['Para usar a coleção, a fila competitiva e a loja você cria uma conta com seu e-mail. Não usamos senha: o acesso é por link enviado ao e-mail, válido por 15 minutos e de uso único. Guardamos apenas o hash do link, a data, e o endereço IP de quem pediu (para evitar abuso).', 'Guardamos também o nome de exibição e o nome do time que você escolher, e um token de sessão (válido por 30 dias) que fica no seu navegador. Sair da conta invalida a sessão.'] },
      { heading: 'Coleção, temporada e ranking', paragraphs: ['Registramos suas cartas, coins, o histórico de movimentações de coins, o time salvo, pontos, títulos e prêmios da temporada. O nome do time e o nome de exibição aparecem no ranking público da temporada. O e-mail nunca aparece para outros jogadores.'] },
      { heading: 'Compras', paragraphs: ['Os pagamentos são processados pelo Mercado Pago. Nós não recebemos nem guardamos número de cartão ou dados bancários. Guardamos o pacote comprado, valor, status, número da transação e os dados do pagamento que o Mercado Pago nos devolve (valor, moeda, status, meio de pagamento), para creditar as coins, tratar estornos e cumprir obrigações legais.', 'O tratamento feito pelo Mercado Pago segue a política de privacidade do próprio Mercado Pago.'] },
      { heading: 'Suporte e reclamações de carta', paragraphs: ['Quando você usa a página de suporte, guardamos seu e-mail, o nome (se informado), a mensagem, o número da transação ou o jogador reportado, com um número de protocolo. Usamos isso só para responder e corrigir o problema.'] },
      { heading: 'Para que usamos os dados', paragraphs: ['Executar o serviço que você pediu: conta, coleção, partidas e compras (execução de contrato). Segurança e prevenção de fraude: limites de tentativas, bloqueio de compras após contestação indevida (legítimo interesse). Guardar registros de compra pelo prazo exigido em lei (obrigação legal). Responder ao seu contato.', 'Não vendemos dados pessoais, não usamos seus dados para publicidade e não usamos cookies de rastreamento.'] },
      { heading: 'Com quem compartilhamos', paragraphs: ['Apenas com os serviços necessários para o funcionamento: Mercado Pago (pagamentos), Resend (envio de e-mails de login e suporte), Railway (servidor e banco de dados) e Vercel (hospedagem do site). Alguns desses serviços podem processar dados fora do Brasil, com as salvaguardas previstas na LGPD. Esses serviços também registram dados técnicos de acesso, como endereço IP, em seus próprios logs.'] },
      { heading: 'Por quanto tempo guardamos', paragraphs: ['Dados da conta e da coleção: enquanto a conta existir. Registros de compras e de coins: pelo prazo exigido pela legislação fiscal e de defesa do consumidor (em geral, 5 anos), mesmo após a exclusão da conta. Mensagens de suporte: pelo tempo necessário para o atendimento e o histórico dele. Links de login e sessões expiram sozinhos.'] },
      { heading: 'Seus direitos', paragraphs: ['Você pode pedir confirmação de tratamento, acesso, correção, portabilidade, informação sobre compartilhamento e exclusão dos seus dados, e revogar consentimentos. Peça pela página de suporte (assunto "Conta / login") ou por contato@cs13a0.com. Respondemos em até 15 dias. Na exclusão, removemos e-mail e perfil; registros de compra que a lei obriga a manter ficam guardados sem uso para outra finalidade.'] },
      { heading: 'Menores de idade', paragraphs: ['Se você tem menos de 18 anos, use a conta e faça compras apenas com autorização do seu responsável legal.'] },
      { heading: 'Segurança', paragraphs: ['Toda comunicação usa HTTPS. Links de login e sessões são guardados apenas como hash. Os pagamentos são confirmados diretamente com o Mercado Pago, nunca pelo navegador. Se algo acontecer com seus dados, avisaremos você e as autoridades conforme a lei.'] },
      { heading: 'Mudanças nesta política', paragraphs: ['Podemos atualizar esta política quando o jogo mudar. A data no topo indica a versão atual; mudanças relevantes serão avisadas no site.'] }
    ]
  },
  en: {
    title: 'Privacy Policy',
    updated: 'Last updated: 2026-09-18',
    intro: 'This policy explains which data cs13a0 processes, why, who it is shared with and how to exercise your rights under Brazil\'s General Data Protection Law (LGPD, Law 13,709/2018). cs13a0 is an independent project run by an individual in Brazil. Contact: contato@cs13a0.com.',
    sections: [
      { heading: 'Playing without an account', paragraphs: ['Offline mode and the online draft work without signing up. Preferences (language, theme, speed) and your last run stay in your browser\'s localStorage and are not sent to us.', 'In online rooms, player name, organization name, picks and results live in server memory only while the room exists. An anonymous resume token stays in your browser for a few minutes.'] },
      { heading: 'Account (optional)', paragraphs: ['The collection, competitive queue and shop require an account created with your e-mail. There is no password: you sign in with a link sent to your e-mail, valid for 15 minutes and usable once. We store only the link hash, the date and the IP address that requested it (to prevent abuse).', 'We also store the display name and team name you choose, and a session token (valid for 30 days) kept in your browser. Logging out invalidates the session.'] },
      { heading: 'Collection, season and ranking', paragraphs: ['We record your cards, coins, coin history, saved team, points, titles and season awards. Your team name and display name appear in the public season ranking. Your e-mail is never shown to other players.'] },
      { heading: 'Purchases', paragraphs: ['Payments are processed by Mercado Pago. We never receive or store card numbers or bank details. We store the pack bought, amount, status, transaction number and the payment data Mercado Pago returns to us (amount, currency, status, payment method) to credit coins, handle refunds and meet legal obligations.', 'Mercado Pago\'s processing follows Mercado Pago\'s own privacy policy.'] },
      { heading: 'Support and rating reports', paragraphs: ['When you use the support page we store your e-mail, name (if given), message, transaction number or reported player, with a ticket number. We use it only to answer and fix the issue.'] },
      { heading: 'Why we use data', paragraphs: ['To provide the service you asked for: account, collection, matches and purchases (contract). Security and fraud prevention: attempt limits, blocking purchases after an improper chargeback (legitimate interest). Keeping purchase records for the period required by law (legal obligation). Answering your messages.', 'We do not sell personal data, do not use it for advertising and do not use tracking cookies.'] },
      { heading: 'Who we share it with', paragraphs: ['Only the services needed to run the game: Mercado Pago (payments), Resend (login and support e-mails), Railway (server and database) and Vercel (site hosting). Some of them may process data outside Brazil with the safeguards required by the LGPD. These services also keep technical access data, such as IP addresses, in their own logs.'] },
      { heading: 'How long we keep it', paragraphs: ['Account and collection data: while the account exists. Purchase and coin records: for the period required by tax and consumer law (usually 5 years), even after the account is deleted. Support messages: as long as needed to handle them and keep their history. Login links and sessions expire on their own.'] },
      { heading: 'Your rights', paragraphs: ['You can ask for confirmation, access, correction, portability, information about sharing and deletion of your data, and withdraw consent. Ask through the support page (subject "Account / login") or at contato@cs13a0.com. We answer within 15 days. On deletion we remove your e-mail and profile; purchase records the law requires us to keep are retained and not used for anything else.'] },
      { heading: 'Minors', paragraphs: ['If you are under 18, use the account and make purchases only with your legal guardian\'s permission.'] },
      { heading: 'Security', paragraphs: ['All traffic uses HTTPS. Login links and sessions are stored only as hashes. Payments are confirmed directly with Mercado Pago, never by the browser. If an incident affects your data, we will notify you and the authorities as the law requires.'] },
      { heading: 'Changes', paragraphs: ['We may update this policy as the game changes. The date at the top shows the current version; relevant changes will be announced on the site.'] }
    ]
  },
  es: {
    title: 'Política de Privacidad',
    updated: 'Última actualización: 18/09/2026',
    intro: 'Esta política explica qué datos trata cs13a0, para qué, con quién los comparte y cómo ejercer tus derechos según la Ley General de Protección de Datos de Brasil (LGPD, Ley 13.709/2018). cs13a0 es un proyecto independiente mantenido por una persona física en Brasil. Contacto: contato@cs13a0.com.',
    sections: [
      { heading: 'Jugar sin cuenta', paragraphs: ['El modo offline y el draft online funcionan sin registro. Las preferencias (idioma, tema, velocidad) y la última partida quedan en el localStorage de tu navegador y no se nos envían.', 'En las salas online, el nombre del jugador, de la organización, los picks y resultados están en la memoria del servidor solo mientras la sala existe. Un token anónimo de reconexión queda en tu navegador por unos minutos.'] },
      { heading: 'Cuenta (opcional)', paragraphs: ['La colección, la cola competitiva y la tienda requieren una cuenta creada con tu correo. No hay contraseña: entras con un enlace enviado a tu correo, válido por 15 minutos y de un solo uso. Guardamos solo el hash del enlace, la fecha y la dirección IP que lo pidió (para evitar abusos).', 'También guardamos el nombre visible y el nombre del equipo que elijas, y un token de sesión (válido por 30 días) en tu navegador. Cerrar sesión la invalida.'] },
      { heading: 'Colección, temporada y ranking', paragraphs: ['Registramos tus cartas, coins, el historial de coins, el equipo guardado, puntos, títulos y premios de la temporada. El nombre del equipo y el nombre visible aparecen en el ranking público. Tu correo nunca se muestra a otros jugadores.'] },
      { heading: 'Compras', paragraphs: ['Los pagos los procesa Mercado Pago. No recibimos ni guardamos números de tarjeta ni datos bancarios. Guardamos el paquete comprado, valor, estado, número de transacción y los datos del pago que Mercado Pago nos devuelve (valor, moneda, estado, medio de pago) para acreditar coins, tratar reembolsos y cumplir obligaciones legales.', 'El tratamiento de Mercado Pago sigue su propia política de privacidad.'] },
      { heading: 'Soporte y reportes de cartas', paragraphs: ['Al usar la página de soporte guardamos tu correo, nombre (si lo das), mensaje, número de transacción o jugador reportado, con un número de protocolo. Solo lo usamos para responder y corregir el problema.'] },
      { heading: 'Para qué usamos los datos', paragraphs: ['Prestar el servicio que pediste: cuenta, colección, partidas y compras (contrato). Seguridad y prevención de fraude: límites de intentos, bloqueo de compras tras un contracargo indebido (interés legítimo). Conservar registros de compra por el plazo legal (obligación legal). Responder tus mensajes.', 'No vendemos datos personales, no los usamos para publicidad ni usamos cookies de rastreo.'] },
      { heading: 'Con quién los compartimos', paragraphs: ['Solo con los servicios necesarios: Mercado Pago (pagos), Resend (correos de acceso y soporte), Railway (servidor y base de datos) y Vercel (alojamiento del sitio). Algunos pueden procesar datos fuera de Brasil con las salvaguardas de la LGPD. Estos servicios también guardan datos técnicos de acceso, como la IP, en sus propios registros.'] },
      { heading: 'Cuánto tiempo los guardamos', paragraphs: ['Datos de cuenta y colección: mientras la cuenta exista. Registros de compras y coins: por el plazo exigido por la ley fiscal y de consumo (en general, 5 años), incluso tras borrar la cuenta. Mensajes de soporte: el tiempo necesario para atenderlos y conservar su historial. Enlaces de acceso y sesiones caducan solos.'] },
      { heading: 'Tus derechos', paragraphs: ['Puedes pedir confirmación, acceso, corrección, portabilidad, información sobre compartición y eliminación de tus datos, y revocar consentimientos. Pídelo en la página de soporte (asunto "Cuenta / login") o en contato@cs13a0.com. Respondemos en hasta 15 días. Al eliminar, borramos correo y perfil; los registros de compra que la ley obliga a guardar se conservan sin otro uso.'] },
      { heading: 'Menores de edad', paragraphs: ['Si tienes menos de 18 años, usa la cuenta y compra solo con autorización de tu responsable legal.'] },
      { heading: 'Seguridad', paragraphs: ['Todo el tráfico usa HTTPS. Los enlaces de acceso y las sesiones se guardan solo como hash. Los pagos se confirman directamente con Mercado Pago, nunca por el navegador. Si un incidente afecta tus datos, te avisaremos a ti y a las autoridades según la ley.'] },
      { heading: 'Cambios', paragraphs: ['Podemos actualizar esta política cuando el juego cambie. La fecha arriba indica la versión actual; los cambios relevantes se avisarán en el sitio.'] }
    ]
  }
};

const TERMS: Record<Language, LegalDocument> = {
  'pt-BR': {
    title: 'Termos de Uso',
    updated: 'Última atualização: 18/09/2026',
    intro: 'Ao usar o cs13a0 você concorda com estes termos. Se não concordar, não use o site. Dúvidas: contato@cs13a0.com ou a página de suporte.',
    sections: [
      { heading: 'O projeto', paragraphs: ['O cs13a0 é um jogo independente de simulação criado por fãs. Não é afiliado, patrocinado ou aprovado por Valve, HLTV, Liquipedia, times, organizações ou jogadores. Counter-Strike e marcas relacionadas pertencem aos seus donos.', 'Dados históricos vêm de fontes públicas (veja a página de créditos). Overalls, funções e atributos são adaptados para o jogo e não são um ranking oficial. Encontrou algo errado? Use "Overall errado" na página de suporte.'] },
      { heading: 'Conta', paragraphs: ['A conta é opcional e pessoal, criada com seu e-mail. Você é responsável pelo acesso ao seu e-mail e não deve compartilhar links de login. Podemos suspender ou encerrar contas usadas para fraude, abuso, automação (bots) ou exploração de falhas.'] },
      { heading: 'Coins e cartas', paragraphs: ['Coins e cartas são itens virtuais: você recebe uma licença pessoal, limitada e intransferível para usá-los dentro do jogo. Eles não têm valor em dinheiro, não podem ser trocados por dinheiro nem vendidos ou transferidos fora do jogo, e não são propriedade sua fora dele.', 'O conteúdo dos pacotes é aleatório; as chances de cada raridade ficam visíveis na loja antes da compra. Podemos ajustar overalls, chances, preços de pacotes, recompensas e regras para manter o jogo equilibrado.'] },
      { heading: 'Compras de coins', paragraphs: ['As compras são feitas em reais, pelo Mercado Pago (Pix ou cartão), com o preço exibido antes do pagamento. As coins são creditadas quando o Mercado Pago aprova o pagamento: no Pix costuma ser na hora; no cartão pode levar alguns minutos. Existe um limite diário de compras por conta.', 'Menores de 18 anos só podem comprar com autorização do responsável legal.'] },
      { heading: 'Arrependimento, reembolso e estorno', paragraphs: ['Você pode desistir da compra em até 7 dias (art. 49 do Código de Defesa do Consumidor) se as coins compradas ainda não tiverem sido usadas: peça pela página de suporte e devolvemos o valor pelo Mercado Pago, removendo as coins.', 'Coins já usadas não são reembolsáveis, exceto por erro nosso ou quando a lei exigir. Se uma compra foi cobrada e as coins não caíram, ou houve cobrança em dobro, fale com o suporte: corrigimos ou devolvemos.', 'Em estorno ou contestação (chargeback), as coins daquela compra são removidas do saldo. Contestação indevida pode bloquear novas compras na conta.'] },
      { heading: 'Conduta', paragraphs: ['Não use o jogo para assédio, spam, abuso dos formulários, automação, ataques ao servidor ou exploração de falhas para ganhar coins ou vantagens. Se encontrar um bug, reporte pelo suporte.'] },
      { heading: 'Disponibilidade e mudanças', paragraphs: ['O site pode ficar fora do ar para manutenção. Salas online podem expirar e partidas em andamento podem ser encerradas se o servidor reiniciar. Podemos mudar ou encerrar modos do jogo; quando isso afetar coins compradas, avisaremos com antecedência razoável.'] },
      { heading: 'Responsabilidade', paragraphs: ['O jogo é oferecido como está. Respondemos pelos serviços que prestamos nos limites da lei, incluindo o Código de Defesa do Consumidor, que nada nestes termos afasta.'] },
      { heading: 'Lei aplicável', paragraphs: ['Estes termos seguem a lei brasileira. Consumidores podem usar o foro do próprio domicílio.'] },
      { heading: 'Mudanças nestes termos', paragraphs: ['Podemos atualizar estes termos. A data no topo indica a versão atual; mudanças relevantes serão avisadas no site. Compras já feitas seguem os termos da data da compra.'] }
    ]
  },
  en: {
    title: 'Terms of Use',
    updated: 'Last updated: 2026-09-18',
    intro: 'By using cs13a0 you agree to these terms. If you do not agree, do not use the site. Questions: contato@cs13a0.com or the support page.',
    sections: [
      { heading: 'The project', paragraphs: ['cs13a0 is an independent fan-made simulation game. It is not affiliated with, sponsored or endorsed by Valve, HLTV, Liquipedia, teams, organizations or players. Counter-Strike and related marks belong to their owners.', 'Historical data comes from public sources (see the credits page). Ratings, roles and attributes are adapted for gameplay and are not an official ranking. Found something wrong? Use "Wrong rating" on the support page.'] },
      { heading: 'Account', paragraphs: ['The account is optional and personal, created with your e-mail. You are responsible for access to your e-mail and must not share login links. We may suspend or close accounts used for fraud, abuse, automation (bots) or exploiting bugs.'] },
      { heading: 'Coins and cards', paragraphs: ['Coins and cards are virtual items: you get a personal, limited, non-transferable licence to use them inside the game. They have no cash value, cannot be exchanged for money, sold or transferred outside the game, and are not your property outside it.', 'Pack contents are random; the odds for each rarity are shown in the shop before you buy. We may adjust ratings, odds, pack prices, rewards and rules to keep the game balanced.'] },
      { heading: 'Buying coins', paragraphs: ['Purchases are in Brazilian reais through Mercado Pago (Pix or card), with the price shown before payment. Coins are credited once Mercado Pago approves the payment: Pix is usually instant; cards may take a few minutes. There is a daily purchase limit per account.', 'Under-18s may only buy with a legal guardian\'s permission.'] },
      { heading: 'Withdrawal, refunds and chargebacks', paragraphs: ['You may cancel a purchase within 7 days (art. 49 of the Brazilian Consumer Code) if the coins bought have not been used: ask through the support page and we refund through Mercado Pago and remove the coins.', 'Coins already used are not refundable, except for our error or where the law requires. If you were charged and the coins did not arrive, or you were charged twice, contact support: we fix it or refund.', 'On a refund or chargeback, the coins from that purchase are removed from your balance. An improper chargeback may block further purchases on the account.'] },
      { heading: 'Conduct', paragraphs: ['Do not use the game for harassment, spam, form abuse, automation, attacks on the server or exploiting bugs to gain coins or advantages. If you find a bug, report it through support.'] },
      { heading: 'Availability and changes', paragraphs: ['The site may go down for maintenance. Online rooms may expire and matches in progress may end if the server restarts. We may change or end game modes; when that affects purchased coins, we will give reasonable notice.'] },
      { heading: 'Liability', paragraphs: ['The game is provided as is. We are liable for our services within the limits of the law, including the Brazilian Consumer Code, which nothing in these terms overrides.'] },
      { heading: 'Governing law', paragraphs: ['These terms are governed by Brazilian law. Consumers may use the courts of their own domicile.'] },
      { heading: 'Changes to these terms', paragraphs: ['We may update these terms. The date at the top shows the current version; relevant changes will be announced on the site. Past purchases follow the terms in force on the purchase date.'] }
    ]
  },
  es: {
    title: 'Términos de Uso',
    updated: 'Última actualización: 18/09/2026',
    intro: 'Al usar cs13a0 aceptas estos términos. Si no estás de acuerdo, no uses el sitio. Dudas: contato@cs13a0.com o la página de soporte.',
    sections: [
      { heading: 'El proyecto', paragraphs: ['cs13a0 es un juego independiente de simulación creado por fans. No está afiliado, patrocinado ni aprobado por Valve, HLTV, Liquipedia, equipos, organizaciones o jugadores. Counter-Strike y las marcas relacionadas pertenecen a sus dueños.', 'Los datos históricos vienen de fuentes públicas (ver créditos). Overalls, roles y atributos están adaptados al juego y no son un ranking oficial. ¿Algo está mal? Usa "Overall incorrecto" en la página de soporte.'] },
      { heading: 'Cuenta', paragraphs: ['La cuenta es opcional y personal, creada con tu correo. Eres responsable del acceso a tu correo y no debes compartir enlaces de acceso. Podemos suspender o cerrar cuentas usadas para fraude, abuso, automatización (bots) o explotación de fallos.'] },
      { heading: 'Coins y cartas', paragraphs: ['Coins y cartas son objetos virtuales: recibes una licencia personal, limitada e intransferible para usarlos dentro del juego. No tienen valor en dinero, no se pueden cambiar por dinero, vender ni transferir fuera del juego, y no son tu propiedad fuera de él.', 'El contenido de los paquetes es aleatorio; las probabilidades de cada rareza se muestran en la tienda antes de comprar. Podemos ajustar overalls, probabilidades, precios, recompensas y reglas para mantener el equilibrio.'] },
      { heading: 'Compra de coins', paragraphs: ['Las compras son en reales, por Mercado Pago (Pix o tarjeta), con el precio mostrado antes del pago. Las coins se acreditan cuando Mercado Pago aprueba el pago: con Pix suele ser inmediato; con tarjeta puede tardar unos minutos. Hay un límite diario de compras por cuenta.', 'Los menores de 18 años solo pueden comprar con autorización de su responsable legal.'] },
      { heading: 'Desistimiento, reembolso y contracargo', paragraphs: ['Puedes desistir de la compra en hasta 7 días (art. 49 del Código de Defensa del Consumidor de Brasil) si las coins no se han usado: pídelo en la página de soporte y devolvemos el valor por Mercado Pago, retirando las coins.', 'Las coins ya usadas no son reembolsables, salvo error nuestro o cuando la ley lo exija. Si te cobraron y las coins no llegaron, o hubo cobro doble, habla con soporte: lo corregimos o devolvemos.', 'En un reembolso o contracargo, las coins de esa compra se retiran del saldo. Un contracargo indebido puede bloquear nuevas compras en la cuenta.'] },
      { heading: 'Conducta', paragraphs: ['No uses el juego para acoso, spam, abuso de formularios, automatización, ataques al servidor o explotación de fallos para ganar coins o ventajas. Si encuentras un bug, repórtalo por soporte.'] },
      { heading: 'Disponibilidad y cambios', paragraphs: ['El sitio puede caer por mantenimiento. Las salas online pueden expirar y las partidas en curso pueden terminar si el servidor se reinicia. Podemos cambiar o cerrar modos de juego; si eso afecta coins compradas, avisaremos con antelación razonable.'] },
      { heading: 'Responsabilidad', paragraphs: ['El juego se ofrece tal cual. Respondemos por nuestros servicios dentro de los límites de la ley, incluido el Código de Defensa del Consumidor, que nada en estos términos excluye.'] },
      { heading: 'Ley aplicable', paragraphs: ['Estos términos se rigen por la ley brasileña. Los consumidores pueden usar el foro de su propio domicilio.'] },
      { heading: 'Cambios en estos términos', paragraphs: ['Podemos actualizar estos términos. La fecha arriba indica la versión actual; los cambios relevantes se avisarán en el sitio. Las compras hechas siguen los términos vigentes en la fecha de compra.'] }
    ]
  }
};

const pick = (language: string): Language => (language === 'en' || language === 'es' ? language : 'pt-BR');
export const privacyPolicy = (language: string): LegalDocument => PRIVACY[pick(language)];
export const termsOfUse = (language: string): LegalDocument => TERMS[pick(language)];
