import type { Language } from '../types';

const online = {
  'pt-BR': {
    playOnline: 'Jogar online', title: 'Major online', intro: 'Crie uma sala efêmera ou entre com um código. Sem conta e sem histórico.', host: 'Criar sala', join: 'Entrar na sala', playerName: 'Seu nome', orgName: 'Nome da organização', roomCode: 'Código da sala', lobby: 'Lobby', copyLink: 'Copiar link', participants: 'Participantes', disconnected: 'Desconectado', connected: 'Conectado', connecting: 'Conectando', reconnecting: 'Reconectando', start: 'Iniciar Major', startRound: 'Iniciar rodada do Major', waitingHost: 'Aguardando o host iniciar a rodada', live: 'Ao vivo', capacity: 'Capacidade', entryStage: 'Entrada', deadline: 'Prazo do draft', speed: 'Velocidade', draft: 'Draft online', draw: 'Sortear time', reroll: 'Rerollar', choose: 'Escolher', style: 'Estilo', waiting: 'Aguardando os outros jogadores', currentGame: 'Minha partida', allGames: 'Visão do Major', standings: 'Tabela', bracket: 'Chaveamento', buchholz: 'Buchholz', wins: 'V', losses: 'D', noGames: 'Aguardando os primeiros resultados', champion: 'Campeão', back: 'Voltar', shareRoom: 'Link da sala copiado', completeRoles: 'Defina cinco funções únicas', configurePro: 'Confirmar PRO', deadlineOff: 'Sem prazo'
  },
  en: {
    playOnline: 'Play online', title: 'Online Major', intro: 'Create an ephemeral room or join with a code. No account and no history.', host: 'Create room', join: 'Join room', playerName: 'Your name', orgName: 'Organization name', roomCode: 'Room code', lobby: 'Lobby', copyLink: 'Copy link', participants: 'Participants', disconnected: 'Disconnected', connected: 'Connected', connecting: 'Connecting', reconnecting: 'Reconnecting', start: 'Start Major', startRound: 'Start Major round', waitingHost: 'Waiting for the host to start the round', live: 'Live', capacity: 'Capacity', entryStage: 'Entry stage', deadline: 'Draft deadline', speed: 'Speed', draft: 'Online draft', draw: 'Draw team', reroll: 'Reroll', choose: 'Choose', style: 'Style', waiting: 'Waiting for the other players', currentGame: 'My match', allGames: 'Major overview', standings: 'Standings', bracket: 'Bracket', buchholz: 'Buchholz', wins: 'W', losses: 'L', noGames: 'Waiting for the first results', champion: 'Champion', back: 'Back', shareRoom: 'Room link copied', completeRoles: 'Assign five unique roles', configurePro: 'Confirm PRO', deadlineOff: 'No deadline'
  },
  es: {
    playOnline: 'Jugar online', title: 'Major online', intro: 'Crea una sala efímera o entra con un código. Sin cuenta ni historial.', host: 'Crear sala', join: 'Entrar a la sala', playerName: 'Tu nombre', orgName: 'Nombre de la organización', roomCode: 'Código de sala', lobby: 'Lobby', copyLink: 'Copiar enlace', participants: 'Participantes', disconnected: 'Desconectado', connected: 'Conectado', connecting: 'Conectando', reconnecting: 'Reconectando', start: 'Iniciar Major', startRound: 'Iniciar ronda del Major', waitingHost: 'Esperando que el host inicie la ronda', live: 'En vivo', capacity: 'Capacidad', entryStage: 'Entrada', deadline: 'Plazo del draft', speed: 'Velocidad', draft: 'Draft online', draw: 'Sortear equipo', reroll: 'Reroll', choose: 'Elegir', style: 'Estilo', waiting: 'Esperando a los otros jugadores', currentGame: 'Mi partido', allGames: 'Vista del Major', standings: 'Tabla', bracket: 'Llaves', buchholz: 'Buchholz', wins: 'V', losses: 'D', noGames: 'Esperando los primeros resultados', champion: 'Campeón', back: 'Volver', shareRoom: 'Enlace de sala copiado', completeRoles: 'Asigna cinco funciones únicas', configurePro: 'Confirmar PRO', deadlineOff: 'Sin plazo'
  }
} as const;

export type OnlineTranslationKey = keyof typeof online['pt-BR'];
export const translateOnline = (language: Language, key: OnlineTranslationKey) => online[language][key];
